[project]
name = "test_project"
version = "0.1.0"
description = "Bioinformatics analysis pipeline"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "jupyter",
    "matplotlib",
    "seaborn"
]

[tool.uv.pip]
compile = true
